# Generated by Django 4.1.2 on 2022-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Object',
        ),
    ]
