# Generated by Django 4.1.2 on 2022-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_rename_user_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('quantiy', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
